# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59ed279335640fc40653f67fb11a84cb5aad796376d2835c760476cb8a23f59714842ff5ce90251151460534b896a20846a485dcde5a272e93171ce9233f68ff

test:
  secret_key_base: 48c8864536ff729b508cf9a68865878b84d4406a616143e031787c6b9b6c4e71bf9ee7f4b3abc066185c17acf9b365d47391418d030918abbb848bb40c247a19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
